# ~/.tmux.conf

unbind r
bind r source-file $HOME/.tmux.conf

set -g prefix C-s
unbind C-b

set -g mouse on
set-option -g status-position top

# List of plugins

# Save and restore sessions automatically
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @continuum-restore 'on'

# Catppuccin Tmux theme
set -g @plugin 'catppuccin/tmux'
set -g @catppuccin_flavour 'mocha'  # or frappe, macchiato, mocha

# Tell Catppuccin (before it runs) what we want for tabs
# set -g @catppuccin_window_status_format " #I:#W "
# set -g @catppuccin_window_status_current_format " #[bold]#I:#W "

# Init and run catppuccin
# run '$HOME/.tmux/plugins/tmux/catppuccin.tmux'

# Make the status line pretty and add some modules
set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""

set -g status-right "#{E:@catppuccin_status_application}"
set -agF status-right "#{E:@catppuccin_status_cpu}"
set -ag  status-right "#{E:@catppuccin_status_session}"
set -ag  status-right "#{E:@catppuccin_status_uptime}"
set -agF status-right "#{E:@catppuccin_status_battery}"

# Misc niceties
set -g window-status-separator " "
set -g window-status-activity-style "underscore"
set -g renumber-windows on
set -s escape-time 10

# Initialize supporting plugins
run "$HOME/.tmux/plugins/tmux-cpu/cpu.tmux"
run "$HOME/.tmux/plugins/tmux-battery/battery.tmux"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '$HOME/.tmux/plugins/tpm/tpm'

##### ---- FINAL OVERRIDES: these MUST be last ----
# Left: show session name only
set -g status-left " #[bold]#S "
# Tabs: index:name
set -g window-status-format " #I:#W "
set -g window-status-current-format " #[bold]#I:#W "
